### ISSUE TITLE
webapp > SignalK Attributes

### ISSUE THREAD

**Issue by Dirk--** [panaaj/sksim#1]
Bug: webapp sets 'value' to string

**Comment by panaaj** [comment]
I assume this issue refers to the `Additional Attributes` screen where values entered are considered sting values.
If this is the case then v.1.1.7 addresses this by sending values:
- that pass the `isNaN()` test as a `number`
- starting with `{` and are valid JSON as an `object`
- that fail the previous tests as `string` 

Value type is reflected in the Value field label.

![image](https://user-images.githubusercontent.com/38519157/50192607-e559a500-0382-11e9-87b1-7127ac024945.png)

**Comment by panaaj** [comment]
v1.1.7 published to NPM (1e422d8)
